<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<<<<<<< HEAD
<testsuite ignored="0" hostname="LAPTOP-7KH0P1KU" failures="1" tests="3" name="Test" time="98.585" errors="0" timestamp="2025-02-08T08:44:08 IST">
  <testcase classname="veer.selenium.selenium.BaseT" name="ARegistrUser" time="10.272"/>
  <testcase classname="veer.selenium.selenium.BaseT" name="BInCorrPass" time="9.686">
    <failure type="java.lang.AssertionError" message="expected [The username and password could not be verified.] but found []">
      <![CDATA[java.lang.AssertionError: expected [The username and password could not be verified.] but found []
at veer.selenium.selenium.BaseT.BInCorrPass(BaseT.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- BInCorrPass -->
  <testcase classname="veer.selenium.selenium.BaseT" name="CLoginFieldBlank" time="7.904"/>
=======
<testsuite ignored="0" hostname="LAPTOP-7KH0P1KU" failures="3" tests="3" name="Test" time="22.154" errors="0" timestamp="2025-07-12T23:39:38 IST">
  <testcase classname="veer.selenium.selenium.BaseT" name="ARegistrUser" time="6.952">
    <failure type="java.lang.AssertionError" message="This username already exists. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: This username already exists. expected [true] but found [false]
at veer.selenium.selenium.POM.Registartion.register(Registartion.java:87)
at veer.selenium.selenium.BaseT.ARegistrUser(BaseT.java:46)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- ARegistrUser -->
  <testcase classname="veer.selenium.selenium.BaseT" name="ARegistrUser" time="6.179">
    <failure type="java.lang.AssertionError" message="This username already exists. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: This username already exists. expected [true] but found [false]
at veer.selenium.selenium.POM.Registartion.register(Registartion.java:87)
at veer.selenium.selenium.BaseT.ARegistrUser(BaseT.java:46)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- ARegistrUser -->
  <testcase classname="veer.selenium.selenium.BaseT" name="ARegistrUser" time="7.516">
    <failure type="java.lang.AssertionError" message="This username already exists. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: This username already exists. expected [true] but found [false]
at veer.selenium.selenium.POM.Registartion.register(Registartion.java:87)
at veer.selenium.selenium.BaseT.ARegistrUser(BaseT.java:46)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- ARegistrUser -->
>>>>>>> 0bbdd3592a8011b54c47fb1918e2b78d61926ea0
</testsuite> <!-- Test -->
